import { StyleSheet } from "react-native";
export const colors = {
  ink: "#0C0F12",
  surface: "#171C20",
  raised: "#20262B",
  line: "#343B41",
  cream: "#F4EDDD",
  muted: "#A6AFB5",
  gold: "#D6B679",
  pink: "#ECAEC9",
  blue: "#A8CDEC",
  green: "#91CFBA",
  danger: "#F6ADB4",
};
export const subjectColor = (slug: string) =>
  ({
    physics: colors.blue,
    chemistry: colors.gold,
    botany: colors.green,
    zoology: colors.pink,
  })[slug] || colors.gold;
export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.ink },
  header: {
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  brand: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 22,
    color: colors.cream,
  },
  eyebrow: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 10,
    letterSpacing: 2,
    color: colors.gold,
    textTransform: "uppercase",
  },
  text: {
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 22,
    color: colors.cream,
  },
  muted: {
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 20,
    color: colors.muted,
  },
  title: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 42,
    lineHeight: 48,
    color: colors.cream,
  },
  sectionTitle: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 26,
    lineHeight: 34,
    color: colors.cream,
  },
  label: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 15,
    lineHeight: 22,
    color: colors.cream,
  },
  small: {
    fontFamily: "Inter_400Regular",
    fontSize: 11,
    lineHeight: 17,
    color: colors.muted,
  },
  body: { flex: 1 },
  scroll: {
    padding: 22,
    gap: 22,
    paddingBottom: 32,
    width: "100%",
    maxWidth: 1280,
    alignSelf: "center",
  },
  row: { flexDirection: "row", alignItems: "center", gap: 12 },
  wrap: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  grow: { flex: 1, minWidth: 0 },
  card: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 22,
    padding: 20,
    gap: 14,
  },
  hero: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 28,
    padding: 26,
    gap: 18,
    overflow: "hidden",
  },
  heroAccent: {
    position: "absolute",
    right: -60,
    top: -80,
    width: 240,
    height: 240,
    borderRadius: 120,
    borderWidth: 1,
    borderColor: "#4A4233",
  },
  heroAccentInner: {
    position: "absolute",
    right: -30,
    top: -50,
    width: 180,
    height: 180,
    borderRadius: 90,
    borderWidth: 1,
    borderColor: "#3A352C",
  },
  stats: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  stat: {
    flex: 1,
    minWidth: 120,
    padding: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    gap: 8,
  },
  number: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 28,
    color: colors.cream,
    fontVariant: ["tabular-nums"],
  },
  button: {
    minHeight: 48,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: colors.raised,
    borderWidth: 1,
    borderColor: colors.line,
  },
  primary: { backgroundColor: colors.gold, borderColor: colors.gold },
  primaryText: {
    color: colors.ink,
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
  },
  iconButton: {
    height: 46,
    width: 46,
    borderRadius: 23,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: "center",
    justifyContent: "center",
  },
  pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] },
  disabled: { opacity: 0.45 },
  input: {
    minHeight: 50,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.ink,
    color: colors.cream,
    fontFamily: "Inter_400Regular",
    fontSize: 16,
  },
  tabbar: {
    padding: 8,
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: colors.line,
    backgroundColor: colors.ink,
    gap: 4,
  },
  tab: {
    flex: 1,
    minHeight: 64,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  tabSelected: { backgroundColor: colors.raised },
  tabLabel: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    color: colors.muted,
  },
  sidebar: {
    width: 190,
    borderRightWidth: 1,
    borderRightColor: colors.line,
    padding: 16,
    gap: 12,
  },
  sidebarTab: {
    minHeight: 56,
    borderRadius: 16,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  error: {
    padding: 16,
    borderRadius: 14,
    backgroundColor: "#2B1F25",
    borderWidth: 1,
    borderColor: "#62414C",
    gap: 10,
  },
  errorText: {
    color: colors.danger,
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 20,
  },
  chip: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.line,
  },
  chipActive: { backgroundColor: colors.raised, borderColor: colors.gold },
  progressTrack: {
    height: 5,
    backgroundColor: colors.line,
    borderRadius: 5,
    overflow: "hidden",
  },
  progressFill: { height: 5, borderRadius: 5 },
  listRow: {
    paddingVertical: 17,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  taskCheck: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: "center",
    justifyContent: "center",
  },
  login: {
    flexGrow: 1,
    padding: 26,
    justifyContent: "center",
    gap: 28,
    width: "100%",
    maxWidth: 520,
    alignSelf: "center",
  },
  divider: { height: 1, backgroundColor: colors.line },
});
