
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const isGenerateCommand = process.argv.some((arg) => arg === "generate");
const databaseUrl =
  process.env.DATABASE_URL ??
  (isGenerateCommand
    ? "postgresql://prisma:prisma@localhost:5432/prisma_generate"
    : env("DATABASE_URL"));

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl,
  },
});
