// Explicit chapter placement. Value: "Target" (all topics go there unless the same topic already exists),
// "*Target" (each topic finds its best home; Target is the fallback), "" (keep as its own chapter).
module.exports.PG_CHMAP = {
  anatomy: { "General anatomy and tissues": "General anatomy & histology", "Upper limb osteology and joints": "Upper limb", "Upper limb muscles and spaces": "Upper limb", "Upper limb neurovascular anatomy": "Upper limb", "Lower limb osteology and joints": "Lower limb", "Lower limb muscles and spaces": "Lower limb", "Lower limb neurovascular anatomy": "Lower limb", "Thoracic wall and mediastinum": "Thorax", "Heart and great vessels": "Thorax", "Lungs, pleura and respiratory anatomy": "Thorax", "Anterior abdominal wall and inguinal region": "Abdomen & pelvis", "Foregut and hepatobiliary anatomy": "Abdomen & pelvis", "Midgut, hindgut and retroperitoneum": "Abdomen & pelvis", "Pelvis and perineum": "Abdomen & pelvis", "Head and neck osteology": "Head & neck", "Head and neck muscles vessels nerves": "Head & neck", "Oral cavity, pharynx and larynx": "Head & neck", "Eye and ear anatomy": "Head & neck", "Neuroanatomy brain and spinal cord": "Neuroanatomy", "Neuroanatomy pathways and circulation": "Neuroanatomy", "General embryology": "Embryology", "Systemic embryology": "Embryology", "General and systemic histology": "General anatomy & histology", "Genetics and developmental anomalies": "Genetics" },
  physiology: { "Cell and membrane physiology": "General & cell physiology", "Blood and hematology": "Blood", "Nerve and muscle": "Nerve & muscle", "Cardiac electrophysiology": "Cardiovascular", "Cardiac hemodynamics": "Cardiovascular", "Blood pressure and circulation": "Cardiovascular", "Respiratory mechanics": "Respiratory", "Gas transport and respiratory control": "Respiratory", "Renal circulation and filtration": "Renal & acid-base", "Renal water electrolyte acid-base": "Renal & acid-base", "Gastrointestinal physiology": "Gastrointestinal", "Endocrine physiology": "Endocrine & reproduction", "Calcium bone reproductive endocrine": "Endocrine & reproduction", "Reproductive physiology": "Endocrine & reproduction", "Central nervous system functions": "Nervous system", "Autonomic and integrated physiology": "Nervous system", "Special senses": "Special senses", "Temperature metabolism and nutrition": "", "Clinical physiological measurements": "" },
  biochemistry: { "Water pH and buffer systems": "Clinical biochemistry", "Carbohydrate chemistry and digestion": "Carbohydrate metabolism", "Glycolysis gluconeogenesis glycogen": "Carbohydrate metabolism", "TCA cycle and oxidative phosphorylation": "Carbohydrate metabolism", "Lipid chemistry and metabolism": "Lipid metabolism", "Cholesterol bile acids and lipoproteins": "Lipid metabolism", "Proteins amino acids enzymes": "*Amino acids & proteins", "Amino acid disorders and urea cycle": "Amino acids & proteins", "Nucleotides purine pyrimidine": "", "DNA replication repair transcription": "Molecular biology", "Translation and molecular biology": "Molecular biology", "Vitamins minerals trace elements": "Vitamins & minerals", "Heme and bilirubin": "Amino acids & proteins", "Hormones and signal transduction": "", "Nutritional clinical biochemistry": "Nutrition & integration", "Organ function tests": "Clinical biochemistry", "Laboratory technology quality control": "Clinical biochemistry", "Oxidative stress and detoxification": "Clinical biochemistry" },
  pathology: { "Cellular, molecular and systemic mechanisms": "*Cell injury & adaptation", "Histopathology principles and morphologic diagnosis": "", "Hematopathology and blood banking": "Haematology", "Systemic organ pathology": "*Other systems", "Cytopathology, molecular pathology and quality": "", "Hematopoiesis and laboratory hematology": "Haematology", "Hematologic malignancies": "Haematology" },
  pharmacology: { "Pharmacokinetics, dynamics and experimental pharmacology": "General pharmacology", "Systemic and organ pharmacology": "*General pharmacology", "Clinical pharmacology, trials and safety": "General pharmacology", "Modern cancer therapeutics and trial design": "Anticancer & immunomodulators" },
  microbiology: { "Clinical microbiology and laboratory operations": "General microbiology", "Bacteriology and resistance": "*General microbiology", "Virology, molecular diagnostics and viral immunology": "Virology", "Mycology and parasitology": "*Parasitology", "Infection control, epidemiology and public health microbiology": "Applied microbiology", "Infectious diseases and antimicrobial stewardship": "Applied microbiology" },
  forensic: { "Forensic examination and legal processes": "Legal procedures & medical law", "Postmortem changes and death": "Thanatology", "Autopsy techniques and interpretation": "Thanatology", "Mechanical injuries": "Injuries", "Asphyxia and neck injuries": "Asphyxial deaths", "Thermal electrical and environmental injuries": "Injuries", "Sexual assault examination": "Sexual offences & infant deaths", "Pregnancy reproduction and infant deaths": "Sexual offences & infant deaths", "Age identification and anthropology": "Identification", "Forensic pathology special cases": "Thanatology", "General toxicology principles": "Toxicology", "Poisoning by pesticides and gases": "Toxicology", "Drug and substance poisoning": "Toxicology", "Metals corrosives and plant poisons": "Toxicology", "Medical jurisprudence and ethics": "Legal procedures & medical law", "Forensic laboratory and DNA": "Identification" },
  community: { "Foundations of public health": "Concepts of health & disease", "Epidemiological measures": "Epidemiology", "Study designs and biases": "Epidemiology", "Screening and diagnostic tests": "Epidemiology", "Biostatistics and data interpretation": "Biostatistics", "Demography and population health": "", "Infectious disease epidemiology": "Communicable diseases", "Noncommunicable disease epidemiology": "Non-communicable diseases", "National health programmes": "Health programmes & care delivery", "Immunization programme": "", "Maternal and child public health": "Maternal & child health", "Nutrition in the community": "Nutrition", "Environmental health and sanitation": "Environment & occupational health", "Occupational and industrial health": "Environment & occupational health", "Health care management and systems": "Health programmes & care delivery", "Social medicine and health education": "", "International health and organizations": "Health programmes & care delivery", "Research ethics and evidence": "Biostatistics" },
  medicine: { "Clinical methods and diagnostic reasoning": "", "Cardiovascular anatomy and physiology": "Cardiology", "Coronary artery disease": "Cardiology", "Heart failure and cardiomyopathy": "Cardiology", "Valvular, pericardial and aortic disease": "Cardiology", "Electrophysiology and rhythm disorders": "Cardiology", "Pulmonary physiology and diagnostics": "Respiratory", "Obstructive airway disease": "Respiratory", "Pulmonary infections": "Respiratory", "Interstitial, vascular and occupational lung disease": "Respiratory", "Gastrointestinal physiology and diagnosis": "Gastroenterology & hepatology", "Esophageal and gastroduodenal disorders": "Gastroenterology & hepatology", "Small bowel and colorectal diseases": "Gastroenterology & hepatology", "Hepatology and liver failure": "Gastroenterology & hepatology", "Pancreatic and biliary disorders": "Gastroenterology & hepatology", "Renal physiology and investigation": "Nephrology", "Acute and chronic kidney disease": "Nephrology", "Glomerular and tubular disease": "Nephrology", "Electrolytes, acid-base and nutrition": "Nephrology", "Endocrine physiology and testing": "Endocrinology", "Diabetes and metabolic disease": "Endocrinology", "Adrenal, reproductive and bone endocrinology": "Endocrinology", "Hematopoiesis and laboratory hematology": "Haematology & oncology", "Anemia, hemostasis and thrombosis": "Haematology & oncology", "Hematologic malignancies": "Haematology & oncology", "General oncology principles": "Haematology & oncology", "Rheumatology and clinical immunology": "Rheumatology", "Infectious diseases and antimicrobial stewardship": "Infectious diseases", "Neurologic localization and diagnostics": "Neurology", "Cerebrovascular and neurocritical disorders": "Neurology", "Chronic neurological disease": "Neurology", "Toxicology, emergency and intensive medicine": "Critical care, poisoning & geriatrics", "Geriatrics and palliative care": "Critical care, poisoning & geriatrics", "Medical dermatology": "", "Medical genetics and genomics": "" },
  surgery: { "Clinical methods and diagnostic reasoning": "", "Operative principles and perioperative care": "General surgery principles", "Trauma, shock and acute surgical care": "General surgery principles", "Esophagogastric, intestinal and colorectal surgery": "Gastrointestinal surgery", "Hepatopancreatobiliary surgery": "Hepatobiliary & pancreas", "Breast, endocrine and soft-tissue surgery": "*Breast", "Vascular and endovascular surgery": "Vascular & lymphatic", "Urological and pelvic surgery": "Urology", "Thoracic and cardiac surgery basics": "Neuro, cardiothoracic & paediatric surgery", "Plastic reconstructive and burn surgery": "", "Neurosurgical principles": "Neuro, cardiothoracic & paediatric surgery", "General pediatric surgical disease": "Neuro, cardiothoracic & paediatric surgery", "Transplant surgery and organ procurement": "", "Surgical oncology techniques": "", "Laparoscopy, robotics and endoscopy": "Orthopaedics & anaesthesia basics in surgery", "General oncology principles": "Surgical oncology techniques", "Electrolytes, acid-base and nutrition": "General surgery principles", "Anesthesia intensive care and resuscitation": "General surgery principles" },
  obg: { "Antenatal care and fetal assessment": "Antenatal care", "High-risk obstetrics and maternal medicine": "Complications of pregnancy", "Labor, delivery and puerperium": "Labour", "Benign gynecology and pelvic disease": "Gynaecology", "Gynecological cancer and prevention": "Gynaecological oncology", "Reproductive endocrinology and infertility": "Gynaecology" },
  paediatrics: { "Clinical methods and diagnostic reasoning": "", "Growth, development and preventive pediatrics": "Growth & development", "Newborn and perinatal medicine": "Neonatology", "Pediatric cardiology": "", "Pediatric respiratory and airway disorders": "", "Pediatric gastroenterology and hepatology": "", "Pediatric nephrology and urinary disease": "", "Pediatric neurology and neurodevelopment": "", "Pediatric hematology-oncology": "", "Pediatric infection, immunology and rheumatology": "", "Pediatric emergency and intensive care": "Paediatric emergencies", "Pediatric endocrine and metabolic genetics": "", "Medical genetics and genomics": "Pediatric endocrine and metabolic genetics", "Electrolytes, acid-base and nutrition": "Paediatric emergencies", "Toxicology, emergency and intensive medicine": "Paediatric emergencies" },
  ophthalmology: { "Ocular anatomy optics and examination": "Anatomy & optics", "Refractive errors and optics": "Anatomy & optics", "Lids lacrimal apparatus and orbit": "Squint, orbit & community", "Conjunctiva and ocular surface": "Anterior segment", "Corneal disease": "Anterior segment", "Lens and cataract": "Anterior segment", "Glaucoma": "Glaucoma", "Uveal and scleral diseases": "Anterior segment", "Retinal vascular disorders": "Retina & optic nerve", "Retinal detachment and macular disease": "Retina & optic nerve", "Neuro-ophthalmology": "Retina & optic nerve", "Pediatric ophthalmology and strabismus": "Squint, orbit & community", "Ocular trauma and emergencies": "", "Ocular infections and public eye health": "Squint, orbit & community" },
  ent: { "Otology and audiovestibular medicine": "Ear", "Rhinology, allergy and anterior skull base": "Nose & sinuses", "Laryngology and head-neck disease": "Pharynx & larynx", "Pediatric ENT, sleep and facial plastic surgery": "" },
  orthopaedics: { "Musculoskeletal anatomy and biomechanics": "", "Fractures, trauma and fixation": "Trauma", "Joint reconstruction and arthritis": "", "Spine and neural orthopaedics": "", "Sports medicine, arthroscopy and soft tissue": "", "Pediatric orthopaedics and deformity": "Regional & paediatric orthopaedics", "Hand, microsurgery and peripheral nerve": "Regional & paediatric orthopaedics", "Musculoskeletal tumors and infection": "Infections & tumours" },
  dermatology: { "Skin anatomy morphology and diagnostics": "Basics & infections", "Blistering disorders": "Inflammatory & immunobullous" },
  psychiatry: { "Psychiatric assessment and foundational science": "", "Mood, psychotic and anxiety disorders": "Major disorders", "Addiction, child and neurodevelopmental psychiatry": "", "Psychiatric treatments, consultation and law": "Other topics", "Geriatrics and palliative care": "" },
  radiology: { "Imaging physics, contrast and radiation safety": "Physics & safety", "Neuroradiology": "", "Abdominal, pelvic and thoracic radiology": "", "Musculoskeletal, breast and pediatric imaging": "", "Image-guided intervention and emergency radiology": "" },
  anaesthesia: { "Anesthesia physiology, pharmacology and preassessment": "General anaesthesia", "Airway management and ventilation": "General anaesthesia", "Anesthetic techniques and monitoring": "General anaesthesia", "Anesthesia for major specialties": "", "Acute/chronic pain and postoperative care": "", "Anesthesia intensive care and resuscitation": "Regional & critical care", "Mechanical ventilation and respiratory failure": "Regional & critical care", "Electrolytes, acid-base and nutrition": "Regional & critical care", "Toxicology, emergency and intensive medicine": "Regional & critical care", "Critical care monitoring and circulatory support": "Regional & critical care" },
};

module.exports.SS_FEEDER_CHMAP = {
  medicine: { "Cardiology": "*Heart failure and cardiomyopathy", "Respiratory medicine": "*Obstructive airway disease", "Gastroenterology & hepatology": "*Hepatology and liver failure", "Nephrology": "*Acute and chronic kidney disease", "Endocrinology & metabolism": "*Diabetes and metabolic disease", "Haematology": "*Anemia, hemostasis and thrombosis", "Neurology": "*Chronic neurological disease", "Rheumatology & immunology": "Rheumatology and clinical immunology", "Infectious diseases": "Infectious diseases and antimicrobial stewardship", "Oncology": "General oncology principles", "Critical care & toxicology": "Toxicology, emergency and intensive medicine", "Genetics, geriatrics & clinical pharmacology": "*Geriatrics and palliative care" },
  surgery: { "Principles of surgery": "Operative principles and perioperative care", "Trauma & burns": "Trauma, shock and acute surgical care", "Head, neck & endocrine": "Breast, endocrine and soft-tissue surgery", "Breast": "Breast, endocrine and soft-tissue surgery", "Upper GI": "Esophagogastric, intestinal and colorectal surgery", "Hepatobiliary & pancreas": "Hepatopancreatobiliary surgery", "Small & large bowel": "Esophagogastric, intestinal and colorectal surgery", "Hernia & abdominal wall": "", "Vascular": "Vascular and endovascular surgery", "Urology": "Urological and pelvic surgery", "Paediatric & plastic surgery basics": "*General pediatric surgical disease", "Oncology & minimal access": "*Surgical oncology techniques" },
  paediatrics: { "Growth, development & nutrition": "Growth, development and preventive pediatrics", "Neonatology": "Newborn and perinatal medicine", "Infectious diseases & immunisation": "Pediatric infection, immunology and rheumatology", "Cardiology": "Pediatric cardiology", "Respiratory": "Pediatric respiratory and airway disorders", "Gastroenterology & hepatology": "Pediatric gastroenterology and hepatology", "Nephrology": "Pediatric nephrology and urinary disease", "Neurology": "Pediatric neurology and neurodevelopment", "Haemato-oncology": "Pediatric hematology-oncology", "Endocrinology & genetics": "Pediatric endocrine and metabolic genetics", "Paediatric emergencies & critical care": "Pediatric emergency and intensive care" },
  obg: { "Reproductive physiology": "Reproductive endocrinology and infertility", "Antenatal & intrapartum care": "*Antenatal care and fetal assessment", "High-risk pregnancy": "High-risk obstetrics and maternal medicine", "Operative obstetrics": "Labor, delivery and puerperium", "Gynaecological endocrinology": "Reproductive endocrinology and infertility", "Infertility": "Reproductive endocrinology and infertility", "Gynaecological oncology": "Gynecological cancer and prevention", "Urogynaecology": "Benign gynecology and pelvic disease", "Contraception & family planning": "" },
  orthopaedics: { "Fractures & trauma": "Fractures, trauma and fixation", "Spine": "Spine and neural orthopaedics", "Arthroplasty & arthritis": "Joint reconstruction and arthritis", "Sports medicine": "Sports medicine, arthroscopy and soft tissue", "Paediatric orthopaedics": "Pediatric orthopaedics and deformity", "Bone tumours & infection": "Musculoskeletal tumors and infection", "Hand & upper limb": "Hand, microsurgery and peripheral nerve" },
  anaesthesia: { "Physiology & pharmacology": "Anesthesia physiology, pharmacology and preassessment", "Airway management": "Airway management and ventilation", "Monitoring": "Anesthetic techniques and monitoring", "Regional anaesthesia": "Anesthetic techniques and monitoring", "Subspecialty anaesthesia": "Anesthesia for major specialties", "Critical care": "Anesthesia intensive care and resuscitation", "Pain medicine": "Acute/chronic pain and postoperative care" },
  radiology: { "Physics & radiation safety": "Imaging physics, contrast and radiation safety", "Neuroradiology": "Neuroradiology", "Chest imaging": "Abdominal, pelvic and thoracic radiology", "Abdominal imaging": "Abdominal, pelvic and thoracic radiology", "Musculoskeletal imaging": "Musculoskeletal, breast and pediatric imaging", "Interventional basics": "Image-guided intervention and emergency radiology", "Paediatric radiology": "Musculoskeletal, breast and pediatric imaging" },
  psychiatry: { "Psychopathology & classification": "Psychiatric assessment and foundational science", "Psychotic disorders": "Mood, psychotic and anxiety disorders", "Mood & anxiety disorders": "Mood, psychotic and anxiety disorders", "Substance use": "Addiction, child and neurodevelopmental psychiatry", "Child psychiatry": "Addiction, child and neurodevelopmental psychiatry", "Psychopharmacology": "Psychiatric treatments, consultation and law", "Psychotherapy": "Psychiatric treatments, consultation and law", "Forensic & legal psychiatry": "Psychiatric treatments, consultation and law" },
  respiratory: { "Airway disease": "Obstructive airway disease", "Infections & TB": "Pulmonary infections", "Interstitial lung disease": "Interstitial, vascular and occupational lung disease", "Pulmonary vascular disease": "Interstitial, vascular and occupational lung disease", "Sleep medicine": "Pleural, mediastinal and sleep disorders", "Lung cancer": "General oncology principles", "Critical care & ventilation": "Mechanical ventilation and respiratory failure" },
  pathology: { "General pathology": "Cellular, molecular and systemic mechanisms", "Haematopathology": "Hematopathology and blood banking", "Systemic pathology": "Systemic organ pathology", "Cytopathology": "Cytopathology, molecular pathology and quality", "Transfusion medicine": "Hematopathology and blood banking", "Molecular pathology": "Cytopathology, molecular pathology and quality" },
  microbiology: { "Bacteriology": "Bacteriology and resistance", "Virology": "Virology, molecular diagnostics and viral immunology", "Mycology": "Mycology and parasitology", "Parasitology": "Mycology and parasitology", "Immunology": "Cellular, molecular and systemic mechanisms", "Hospital infection control": "Infection control, epidemiology and public health microbiology", "Molecular diagnostics": "Clinical microbiology and laboratory operations" },
  pharmacology: { "General pharmacology": "Pharmacokinetics, dynamics and experimental pharmacology", "Systemic pharmacology": "Systemic and organ pharmacology", "Clinical trials & regulation": "Clinical pharmacology, trials and safety", "Pharmacovigilance": "Clinical pharmacology, trials and safety", "Pharmacogenomics": "Medical genetics and genomics" },
  ent: { "Otology": "Otology and audiovestibular medicine", "Rhinology": "Rhinology, allergy and anterior skull base", "Laryngology": "Laryngology and head-neck disease", "Head & neck oncology": "Laryngology and head-neck disease", "Paediatric ENT": "Pediatric ENT, sleep and facial plastic surgery" },
};

// Pasted cross-subject chapters in the SS feeder papers (not part of that PG-exit curriculum).
module.exports.SS_PAPER_DROP = { orthopaedics: ["Plastic reconstructive and burn surgery"], obg: ["Anesthesia physiology, pharmacology and preassessment"], psychiatry: ["Growth, development and preventive pediatrics"], radiodiagnosis: ["Cardiovascular investigations"] };
